### PR TITLE
Fix feathers update method with null id and params criteria

### PR DESCRIPTION
**Pull request by gbevan**
### Summary

FeathersJS [manual](https://docs.feathersjs.com/api/services.html#updateid-data-params) states that the update method has 3 parameters (id, data, params), and "... id can also be null when updating multiple records with params.query containing the query criteria".  Currently feathers-waterline only supports (id, data) and only updates a single record.

This pull request brings feathers-waterline into alignment with the above documentation.

### Other Information

I've also added support for passing through $... controls to the adapter.

### CODE REVIEW

**Comment by daffl** [comment]
Thanks @gbevan! Would you be interested in updating this adapter to the latest service tests (see https://github.com/feathersjs/feathers-waterline/pull/36) which also covers all other documented scenarios?

Otherwise I'll just release this one but there will be other documented cases that this adapter does not support since it is not an official database adapter anymore.

**Comment by gbevan** [comment]
Hi @daffl, i just tried 0.10.2 version of tests, there's about 30 failing (after i fixed the driving of the base() tests).  So, perhaps you could merge this PR as is, and I'll spend some time over the coming weekends to look at adding support for the latest tests.

**Comment by gbevan** [comment]
@daffl you say this isnt an official feathers adaptor anymore, but it is still listed on the feathers Databases page - https://legacy.docs.feathersjs.com/databases/readme.html

Just realised the url says "legacy.docs"...

**Comment by gbevan** [comment]
I've had a quick look at the latest tests and the issues they raise - looks like we would need to upgrade sails-disk to 1.0.0, which in turn depends upon waterline 0.13 which hasnt yet been released. I would suggest waiting for waterline 0.13 and then apply these tests

**Comment by daffl** [comment]
Sounds good. I released this PR as v1.4.0 for now.

**Comment by gbevan** [comment]
Cheers!  I'm using the 1.4.0 npm now.  many thx.

**Pull request merged**
